; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

//--const-start
#define APP_NAME "PolicyTraySwitch"
#define APP_NAME_LONG "Policy Tray Switch"
#define APP_VERSION "1.0.0"
#define APP_EXE_NAME "PolicyTraySwitch.exe"
#define APP_PUBLISHER "IVN-git"
//--const-end


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3FE96B6C-EEC7-4896-9975-C9618FA28A0B}
AppName={#APP_NAME_LONG}
AppVersion={#APP_VERSION}
;AppVerName={#APP_NAME_LONG} {#APP_VERSION}
AppPublisher={#APP_PUBLISHER}
DefaultDirName={autopf}\{#APP_NAME}
UninstallDisplayIcon={app}\{#APP_EXE_NAME}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=lowest
OutputBaseFilename={#APP_NAME}_Setup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\{#APP_NAME}\{#APP_EXE_NAME}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\{#APP_NAME}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#APP_NAME_LONG}"; Filename: "{app}\{#APP_EXE_NAME}"
Name: "{autodesktop}\{#APP_NAME_LONG}"; Filename: "{app}\{#APP_EXE_NAME}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#APP_EXE_NAME}"; Description: "{cm:LaunchProgram,{#StringChange(APP_NAME_LONG, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueName: {#APP_NAME}; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\{#APP_NAME}"; Flags: uninsdeletekey
[Code]
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  // Используем макрос AppExeName через вставку в строку
  Exec('taskkill.exe', '/f /im "{#APP_EXE_NAME}"', '', SW_HIDE,
     ewWaitUntilTerminated, ResultCode);
  Result := True;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  // То же самое при деинсталляции
  Exec('taskkill.exe', '/f /im "{#APP_EXE_NAME}"', '', SW_HIDE,
     ewWaitUntilTerminated, ResultCode);
  Result := True;
end;


